---
title: "R Notebook"
output: html_notebook
---


```{r}
rm(list=ls())
library(data.table)
library(readxl)
cov<-read_excel('/Users/zhaoshaoling/Documents/ABCD_indivTopo/step01_SubjectFilter/age_sex_fd.xlsx') 
demo<-fread('/Users/zhaoshaoling/Documents/ABCD_indivTopo/step01_SubjectFilter/pdem02.txt')
family<-fread('/Users/zhaoshaoling/Documents/ABCD_indivTopo/step01_SubjectFilter/acspsw03.txt')
familyS<-family[which(family$eventname=='baseline_year_1_arm_1'),c('subjectkey','rel_family_id')]
```

#change ABCC ID
```{r}
abcc_demo<-fread('/Users/zhaoshaoling/Documents/ABCD_indivTopo/step01_SubjectFilter/participants5048.csv') # got from ABCC,
abcc_demo=abcc_demo[which(abcc_demo$collection_3165==1),]
temp<-strsplit(abcc_demo$participant_id, "-")
temp1<-do.call(cbind, temp)
temp1=t(temp1)
temp1=as.data.frame(temp1)
abcc_demo$subjectkey<-paste(substr(temp1$V2,1,4), substr(temp1$V2,5,nchar(temp1$V2)), sep = "_")
```

#ifelse( DEMO_ROSTER_V2 %in% c(777,999) | DEMO_ROSTER_V2 > 20 , NA, DEMO_ROSTER_V2
```{r}
cov$subjectkey<-paste(substr(cov$subjectkey,1,4), substr(cov$subjectkey,5,nchar(temp1$V2)), sep = "_")
cov_abcc=merge(cov,abcc_demo[,c('subjectkey','race_ethnicity','income','parental_education','site')],by='subjectkey')
cov_abcc_fam<-merge(cov_abcc,demo[,c('subjectkey','demo_comb_income_v2','demo_roster_v2','interview_date')],by='subjectkey')
cov_abcc_Cov<-merge(cov_abcc_fam,abcc_demo,by='subjectkey') 
```

```{r}
abcd_final<-cov_abcc_Cov[,c('subjectkey','age.x','sex.x','FD','site.x','income.x','demo_roster_v2','race_ethnicity.x','interview_date','matched_group')]
abcd_final$demo_roster_v2=as.numeric(abcd_final$demo_roster_v2)
abcd_final$site=as.numeric(as.factor(abcd_final$site))

```

# select data with more than 20 minutes and motion larger than 0.2
```{r}
abcd_final_DeFD=abcd_final[which(abcd_final$FD<=0.2),]
#abcd_final_DeFD=abcd_final
#cat("After deleted FD>0.2,remaining",nrow(abcd_final_DeFD))


restingInform<-fread("/Users/zhaoshaoling/Documents/ABCD_indivTopo/step01_SubjectFilter/abcd_mrirstv02.txt")
restingInform<-restingInform[which(restingInform$eventname=='baseline_year_1_arm_1'),c('subjectkey','rsfmri_var_numtrs')]
#restingInform_1<-restingInform[which(restingInform$eventname=='baseline_year_1_arm_1'),c('subjectkey','rsfmri_var_nvols')]

datafinal_rest<-merge(abcd_final_DeFD,restingInform,by='subjectkey')
datafinal_rest$rsfmri_var_numtrs<-as.numeric(datafinal_rest$rsfmri_var_numtrs)
datafinal_rest_filter<-datafinal_rest[which(datafinal_rest$rsfmri_var_numtrs>=1500),]
#datafinal_rest_filter<-datafinal_rest[which(datafinal_rest$rsfmri_var_nvols >=1500),]
print(nrow(datafinal_rest_filter))

cat("After selecting resting scanning >20 min,remaining",nrow(datafinal_rest_filter))
write.csv(datafinal_rest_filter,'/Users/zhaoshaoling/Documents/ABCD_indivTopo/step01_SubjectFilter/SES_Topo_Label_cov_finalSample.csv')

```


```{r}
#compute income-to-needs ratio
abcd_final_DeFD_DeMissing=na.omit(datafinal_rest_filter,cols = "income.x")

abcd_final_DeFD_DeMissing_deSES<-abcd_final_DeFD_DeMissing[which(abcd_final_DeFD_DeMissing$income.x<11),]

income_to_median <- function(income) {
  switch(income,
         '1' = 2500,               # "Less than $5,000" median
         '2' = 8500,               # ($5000 + $11999) / 2
         '3' = 13999.5,            # ($12000 + $15999) / 2
         '4' = 20499.5,            # ($16000 + $24999) / 2
         '5' = 29999.5,            # ($25000 + $34999) / 2
         '6' = 42499.5,            # ($35000 + $49999) / 2
         '7' = 62499.5,            # ($50000 + $74999) / 2
         '8' = 87499.5,            # ($75000 + $99999) / 2
         '9' = 149999.5,           # ($100000 + $199999) / 2
         '10' = 200000,            # $200000 (start value)
         NA                        # default is NA
  )
}

abcd_final_DeFD_DeMissing_deSES$income_median <- sapply(abcd_final_DeFD_DeMissing_deSES$income.x, income_to_median)

abcd_final_DeFD_DeMissing_deSES$interviewYear<-substr(abcd_final_DeFD_DeMissing_deSES$interview_date,start=nchar(abcd_final_DeFD_DeMissing_deSES$interview_date)-3, stop=nchar(abcd_final_DeFD_DeMissing_deSES$interview_date))

abcd_final_DeFD_DeMissing_deSES$interviewYear=as.numeric(abcd_final_DeFD_DeMissing_deSES$interviewYear)

# poverty line in the USA
reference_data <- data.frame(familysize = c(1,2,3,4,5,6,7,8,
                                            1,2,3,4,5,6,7,8,
                                            1,2,3,4,5,6,7,8),
                             povertyline = c(12140,16460,20780,25100,29420,33740,38060,42380,
                                             12060,16240,20420,24600,28780,32960,37140,41320,
                                             11880,16020,20160,24300,28440,32580,36730,40890),
                             Year = c(rep(2018,8), rep(2017,8), rep(2016,8)))

# combine data with interviewYear and demo_roster_v2 
abcd_final_DeFD_DeMissing_deSES1 <- merge(abcd_final_DeFD_DeMissing_deSES, reference_data,
                                         by.x = c("interviewYear", "demo_roster_v2"),
                                         by.y = c("Year", "familysize"), 
                                         all.x = TRUE)

abcd_final_DeFD_DeMissing_deSES1$adjIncome<-abcd_final_DeFD_DeMissing_deSES1$income_median/abcd_final_DeFD_DeMissing_deSES1$povertyline

abcd_final_DeFD_DeMissing_deSES=na.omit(abcd_final_DeFD_DeMissing_deSES1)
cat("After filter SES and family Size misising",nrow(abcd_final_DeFD_DeMissing_deSES))
write.csv(abcd_final_DeFD_DeMissing_deSES,'/Users/zhaoshaoling/Documents/ABCD_indivTopo/step01_SubjectFilter/SES_Topo_Label_deFamily_SES.csv')
```



```{r}
abcd_final_DeFD_DeMissing_deSES$imageID<-gsub('_','',abcd_final_DeFD_DeMissing_deSES$subjectkey)
datafinal1<-merge(abcd_final_DeFD_DeMissing_deSES,familyS,by='subjectkey')
datafinal <- datafinal1[!duplicated(datafinal1$rel_family_id), ]
cat('Remaing Sample',nrow(datafinal))
write.csv(datafinal,'/Users/zhaoshaoling/Documents/ABCD_indivTopo/step01_SubjectFilter/SES_Topo_Label_deSiblings.csv')
#write.csv(datafinal,'/Users/zhaoshaoling/Documents/ABCD_indivTopo/step01_SubjectFilter/SES_Topo_Label_cov_finalSample3198.csv')
```




